import { getAiModel } from '../../services/firebaseAIService';
import { Part } from 'firebase/ai';

/**
 * Converts a standard browser File object (Video) into a Firebase AI SDK Part.
 * Uses the native browser FileReader API to extract the Base64 string.
 * @param file The DOM File object from an <input type="file">
 * @returns A Promise that resolves to an InlineData Part object
 */
export async function fileToGenerativePart(file: File): Promise<Part> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = () => {
      const result = reader.result;
      if (typeof result === 'string') {
        const splitResult = result.split(',');
        if (splitResult.length > 1) {
          resolve({
            inlineData: {
              data: splitResult[1],
              mimeType: file.type || 'video/mp4',
            },
          });
          return;
        }
      }
      reject(new Error('Failed to parse video file data as Base64.'));
    };

    reader.onerror = () => reject(reader.error || new Error('Error reading video file.'));
    reader.readAsDataURL(file);
  });
}

// Note: The Gemini API restricts the total size of inline data payloads. 
// To process larger files without hitting HTTP 413 errors (PayLoad Too Large),
// See the official Firebase AI documentation for current file size limits and workarounds:
// https://firebase.google.com/docs/ai-logic/solutions/cloud-storage

/**
 * Sends a video analysis request (prompt + video file) to the Gemini model.
 * @param prompt The string instruction sent to the model (e.g. "Describe what happens in this video").
 * @param videoFile The DOM File object containing the video.
 * @returns The text string response generated by the model.
 */
export async function analyzeVideo(prompt: string, videoFile: File): Promise<string> {
  try {
    const videoPart = await fileToGenerativePart(videoFile);
    const model = getAiModel('gemini-3.5-flash');
    const result = await model.generateContent([prompt, videoPart]);
    return result.response.text();
  } catch (error: unknown) {
    throw error instanceof Error
      ? error
      : new Error('An unknown error occurred during video analysis.');
  }
}

/**
 * Streams the video analysis response from the Gemini model in real-time chunks.
 * @param prompt The string instruction sent to the model.
 * @param videoFile The DOM File object containing the video.
 * @param onChunk Callback fired whenever a new text chunk is received.
 */
export async function streamVideoAnalysis(
  prompt: string,
  videoFile: File,
  onChunk: (chunk: string) => void
): Promise<void> {
  try {
    const videoPart = await fileToGenerativePart(videoFile);
    const model = getAiModel('gemini-3.7-flash');
    const result = await model.generateContentStream([prompt, videoPart]);

    for await (const chunk of result.stream) {
      const chunkText = chunk.text();
      if (chunkText) {
        onChunk(chunkText);
      }
    }
  } catch (error: unknown) {
    throw error instanceof Error
      ? error
      : new Error('An unknown error occurred during video streaming.');
  }
}