import { getAiTemplateModel } from '../../services/firebaseAIService';

export interface InvoiceTemplateVariables {
  customerName: string;
}

/**
 * Executes a server-side prompt template in a single unary request.
 * Centrally managed templates allow updating prompts and models without redeploying client code.
 * 
 * NOTE: DC w/ Christina: Streaming and multi-turn chat are supported by the SDK (generateContentStream / startChat),
 * but omitted here to keep this quickstart sample minimal and focused on variable injection.
 * 
 * @param templateId The ID of the locked template in the Firebase Console (e.g. 'invoice-generator')
 * @param variables Key-value map matching the {{variables}} declared in the template
 * @returns The text string generated by the model
 */
export async function generateFromTemplate(
  templateId: string,
  variables: Record<string, unknown>
): Promise<string> {
  try {
    // TODO: confo if template versioning/alias options should be exposed here
    const model = getAiTemplateModel();
    const result = await model.generateContent(templateId, variables);
    return result.response.text();
  } catch (error: unknown) {
    console.error('Error generating content from server template:', error);
    // TODO: Consider maybe mapping specific SDK error codes if custom error handling is needed
    throw error instanceof Error
      ? error
      : new Error('An unknown error occurred during template generation.');
  }
}
