import { getAiTemplateModel } from '../../services/firebaseAIService';

export interface InvoiceTemplateVariables {
  customerName: string;
}

/**
 * Executes a server-side prompt template in a single unary request.
 * Centrally managed templates allow updating prompts and models without redeploying client code.
 * 
 * @param templateId The ID of the locked template in the Firebase Console (e.g. 'invoice-generator')
 * @param variables Key-value map matching the {{variables}} declared in the template
 * @returns The text string generated by the model
 */
export async function generateFromTemplate(
  templateId: string,
  variables: Record<string, unknown>
): Promise<string> {
  try {
     const model = getAiTemplateModel();
    const result = await model.generateContent(templateId, variables);
    return result.response.text();
  } catch (error: unknown) {
    throw error instanceof Error
      ? error
      : new Error('An unknown error occurred during template generation.');
  }
}
