import { useState, useRef, useEffect } from 'react';
import { ChatSession, ImageConfigAspectRatio } from 'firebase/ai';
import { startImageChat, sendImageChatMessage } from './service';
import { ImageGenerationSegment } from './service';

interface ChatMessage {
  role: 'user' | 'model';
  text?: string;
  segments?: ImageGenerationSegment[];
}

export default function ImageGenerationView() {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [prompt, setPrompt] = useState('Generate an image of the Eiffel Tower with fireworks in the background.');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const chatSessionRef = useRef<ChatSession | null>(null);
  useEffect(() => {
    try {
      chatSessionRef.current = startImageChat(ImageConfigAspectRatio.SQUARE_1x1);
      setError(null);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to initialize chat session. Please check your Firebase configuration.';
      setError(message);
    }
  }, []);

  const handleGenerate = async () => {
    const cleanedPrompt = prompt.trim();
    if (!cleanedPrompt || !chatSessionRef.current) return;
    const files = Array.from(fileInputRef.current?.files ?? []);
    const referenceFile = files.length > 0 ? files[0] : undefined;

    setLoading(true);
    setError(null);
    setPrompt('');

    try {
      setMessages((prev) => [...prev, { role: 'user', text: cleanedPrompt }]);
      const result = await sendImageChatMessage(chatSessionRef.current, cleanedPrompt, referenceFile);
      setMessages((prev) => [...prev, {
        role: 'model',
        segments: result.segments
      }]);

      if (fileInputRef.current) fileInputRef.current.value = '';

    } catch (err: unknown) {
      console.error(err);
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError('An error occurred during image generation.');
      }
    } finally {
      setLoading(false);
    }
  }

  const handleResetChat = () => {
    try {
      chatSessionRef.current = startImageChat(ImageConfigAspectRatio.SQUARE_1x1);
      setMessages([]);
      setError(null);
      setPrompt('');
      if (fileInputRef.current) fileInputRef.current.value = '';
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to reset chat session.';
      setError(message);
    }
  };

  return (
    <div style={{ padding: '20px', maxWidth: '800px', margin: '0 auto', fontFamily: 'sans-serif' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h2>Image Generation & Iterative Editing</h2>
        <button onClick={handleResetChat} style={{ padding: '8px 12px', cursor: 'pointer' }}>
          Reset Session
        </button>
      </div>
      <p style={{ color: '#666', marginBottom: '20px' }}>
        Ask Gemini to generate an image, or upload a reference file and ask the model to edit it iteratively.
      </p>

      {error && (
        <div style={{ padding: '15px', backgroundColor: '#fee', color: '#c00', marginBottom: '20px', borderRadius: '4px' }}>
          {error}
        </div>
      )}

      <div style={{ border: '1px solid #ccc', borderRadius: '8px', padding: '20px', minHeight: '400px', marginBottom: '20px', backgroundColor: '#f9f9f9', display: 'flex', flexDirection: 'column', gap: '20px', overflowY: 'auto', maxHeight: '600px' }}>
        {messages.map((msg, idx) => (
          <div key={idx} style={{ textAlign: msg.role === 'user' ? 'right' : 'left' }}>
            <div style={{ display: 'inline-block', padding: '15px', borderRadius: '8px', backgroundColor: msg.role === 'user' ? '#007bff' : '#e9ecef', color: msg.role === 'user' ? '#fff' : '#000', maxWidth: '85%' }}>
              {msg.text && <p style={{ margin: '0 0 10px 0', whiteSpace: 'pre-wrap' }}>{msg.text}</p>}
              {/* Native browser rendering of the ordered segments */}
              {msg.segments && msg.segments.map((segment, i) => {

                if (segment.type === 'text') {
                  return (
                    <p key={i} style={{ whiteSpace: 'pre-wrap', marginTop: '10px' }}>
                      {segment.text}
                    </p>
                  );
                }

                if (segment.type === 'image') {
                  return (
                    <img
                      key={i}
                      src={`data:${segment.mimeType};base64,${segment.base64}`}
                      alt="Generated by Gemini"
                      style={{ maxWidth: '100%', borderRadius: '4px', marginTop: '10px' }}
                    />
                  );
                }

                return null;
              })}

            </div>
          </div>
        ))}
        {loading && <div style={{ color: '#666', fontStyle: 'italic' }}>Generating content...</div>}
      </div>

      <div style={{ display: 'flex', gap: '10px', flexDirection: 'column' }}>
        <input
          type="file"
          ref={fileInputRef}
          accept="image/*"
          disabled={loading}
          style={{ padding: '5px' }}
        />
        <div style={{ display: 'flex', gap: '10px' }}>
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g., Make the sky purple and add a spaceship..."
            style={{ flex: 1, padding: '10px', borderRadius: '4px', border: '1px solid #ccc' }}
            disabled={loading}
          />
          <button
            onClick={handleGenerate}
            disabled={loading || (!prompt.trim() && !fileInputRef.current?.files?.length)}
            style={{ padding: '10px 20px', borderRadius: '4px', backgroundColor: '#007bff', color: '#fff', border: 'none', cursor: loading ? 'not-allowed' : 'pointer' }}
          >
            Send
          </button>
        </div>
      </div>
    </div>
  );
}