// Service for chat
import { ChatSession } from 'firebase/ai';
import { getAiModel } from '../../services/firebaseAIService';

/**
 * Initializes a new multi-turn chat session.
 * The SDK's ChatSession automatically maintains the conversation history.
 * * @returns A new ChatSession instance.
 */
export function startNewChat(): ChatSession {
  const model = getAiModel('gemini-3.5-flash');
  return model.startChat({
    history: [],
  });
}

/**
 * Sends a message to an existing chat session and returns the response text.
 * * @param chat The active ChatSession instance.
 * @param message The user's message string.
 * @returns The text string response generated by the model.
 */
export async function sendChatMessage(chat: ChatSession, message: string): Promise<string> {
  try {
    const result = await chat.sendMessage(message);
    return result.response.text();
  } catch (error) {
    console.error('Error sending chat message:', error);
    throw error;
  }
}