import { getAiModel } from '../../services/firebaseAIService';
import { Part } from 'firebase/ai';

/**
 * Converts a standard browser File object (Image, PDF, etc.) into a Firebase AI SDK Part.
 * Uses the native browser FileReader API to extract the Base64 string.
 * @param file The DOM File object from an <input type="file">
 * @returns A Promise that resolves to an InlineData Part object
 */
export async function fileToGenerativePart(file: File): Promise<Part> {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onloadend = () => {
            const result = reader.result;
            if (typeof result === 'string') {
                const splitResult = result.split(',');
                if (splitResult.length > 1) {
                    resolve({
                        inlineData: {
                            data: splitResult[1],
                            mimeType: file.type
                        }
                    });
                    return;
                }
            }
            reject(new Error('Failed to parse file data as Base64.'));
        };

        reader.onerror = () => reject(reader.error || new Error('Error reading file.'));
        reader.readAsDataURL(file);
    });
}

/**
 * Sends a multimodal request (text + files) to the Gemini model.
 * @param prompt The string instruction sent to the model.
 * @param files An array of standard DOM File objects.
 * @returns The text string response generated by the model.
 */
export async function generateMultimodalContent(prompt: string, files: File[]): Promise<string> {
    try {
        const fileParts = await Promise.all(files.map(fileToGenerativePart));
        const model = getAiModel('gemini-3.5-flash');
        const result = await model.generateContent([prompt, ...fileParts]);
        return result.response.text();
    } catch (error) {
        console.error('Error generating multimodal content with Firebase AI:', error);
        throw error;
    }
}
