import { getAiModel } from '../../services/firebaseAIService';

/**
 * Generates text from a text prompt.
 * @param prompt The string instruction sent to the model.
 * @returns The text string response generated by the model.
 */
export async function generateText(prompt: string): Promise<string> {
  try {
    const model = getAiModel('gemini-3.5-flash');
    const result = await model.generateContent(prompt);

    return result.response.text(); 
  } catch (error) {
    console.error('Error generating text with Firebase AI:', error);
    throw error;
  }
}

/**
 * Streams text from a text prompt, yielding chunks as they arrive.
 * @param prompt The string instruction sent to the model.
 * @param onChunk Callback fired for each non-empty text chunk.
 */
export async function streamText(prompt: string, onChunk: (chunk: string) => void): Promise<void> {
  try {
    const model = getAiModel('gemini-3.5-flash');
    const result = await model.generateContentStream(prompt);

    for await (const chunk of result.stream) {
      const chunkText = chunk.text();
      if (chunkText) {
        onChunk(chunkText);
      }
    }
  } catch (error) {
    console.error('Error streaming text with Firebase AI:', error);
    throw error;
  }
}

/**
 * Generates text using a specific system instruction to guide the model's behavior.
 * @param systemInstruction The persona or constraints for the model.
 * @param prompt The string instruction sent to the model.
 * @returns The text string response generated by the model.
 */
export async function generateWithSystemInstruction(systemInstruction: string, prompt: string): Promise<string> {
  try {
    const model = getAiModel('gemini-3.5-flash', { systemInstruction });
    
    const result = await model.generateContent(prompt);
    return result.response.text();
  } catch (error) {
    console.error('Error generating text with system instruction:', error);
    throw error;
  }
}