import { getAiModel } from '../../services/firebaseAIService';

/**
 * Generates text from a text prompt, optionally using a system instruction.
 * @param prompt The string instruction sent to the model.
 * @param systemInstruction (Optional) The persona or constraints for the model.
 * @returns The text string response generated by the model.
 */
export async function generateText(prompt: string, systemInstruction?: string): Promise<string> {
  try {
    const options = systemInstruction ? { systemInstruction } : undefined;
    const model = getAiModel('gemini-3.5-flash', options);
    
    const result = await model.generateContent(prompt);
    return result.response.text(); 
  } catch (error) {
    console.error('Error generating text with Firebase AI:', error);
    throw error;
  }
}

/**
 * Streams text from a text prompt, yielding chunks as they arrive.
 * @param prompt The string instruction sent to the model.
 * @param onChunk Callback fired for each non-empty text chunk.
 * @param systemInstruction (Optional) The persona or constraints for the model.
 */
export async function streamText(prompt: string, onChunk: (chunk: string) => void, systemInstruction?: string): Promise<void> {
  try {
    const options = systemInstruction ? { systemInstruction } : undefined;
    const model = getAiModel('gemini-3.5-flash', options);
    
    const result = await model.generateContentStream(prompt);

    for await (const chunk of result.stream) {
      const chunkText = chunk.text();
      if (chunkText) {
        onChunk(chunkText);
      }
    }
  } catch (error) {
    console.error('Error streaming text with Firebase AI:', error);
    throw error;
  }
}